ROI_SIZE = 0.275
ROI_X_START = 0.10
ROI_Y_START = 0.27
BINARY_THRESHOLD = 31
GAUSSIAN_BLUR_VAL = 51
GAUSSIAN_BLUR_FINGERS_COUNT = 31
BG_SUBTRACTION_MODEL_LEARNING_RATE = 0.0003
BG_SUBTRACTION_THRESHOLD = 6
CONVEX_HULL_RELAX_THRESHOLD = 60
DIRECTION_ANGLES_OFFSET = 40

MINIMAL_ACCEPTED_QUANTITY_OF_VERTICES = 3
MIN_CONVEX_HULL_SQUARE_IN_SCREEN_PERCENTAGE = 0.15
MAX_CONVEX_HULL_SQUARE_IN_SCREEN_PERCENTAGE = 0.95

UI_WINDOW_WIDTH = 1280
UI_WINDOW_HEIGHT = 720

BACKGROUND_REMOVER_MODEL_HISTORY_SIZE = 100
BACKGROUND_REMOVER_KERNEL_SIZE = 5

MIN_GESTURE_OFFSET_FROM_FRAME = 40
MIN_GESTURE_ANGLE_OFFSET = 40

NN_IMAGE_INPUT_SIZE = 225
NN_MODEL_WEIGHTS_PATH = "new_best.h5"
NN_GESTURE_CONFIRMATION_SEQUENCE_LENGTH = 9
NN_GESTURE_CONFIRMATION_COUNT = 7