ROI_SIZE = 0.28
ROI_X_START = 0.11
ROI_Y_START = 0.3
BINARY_THRESHOLD = 21
GAUSSIAN_BLUR_VAL = 41
GAUSSIAN_BLUR_FINGERS_COUNT = 41
BG_SUBTRACTION_MODEL_LEARNING_RATE = 0.0001
BG_SUBTRACTION_THRESHOLD = 5
CONVEX_HULL_RELAX_THRESHOLD = 60
DIRECTION_ANGLES_OFFSET = 40

UI_WINDOW_WIDTH = 1080
UI_WINDOW_HEIGHT = 720